### ISSUE TITLE
LBAS resupply FindFailed if LBAS is already resupplied.

### ISSUE THREAD

**Issue by waicool20** [perryhuynh/kcauto#117] opened 2018-03-12 06:22 UTC
*Please read the FAQ section of the kcauto-kai Wiki before opening a ticket. Please remove sections of this template you do not find relevant when creating your ticket.*

#### Environment details

* kcauto-kai version (date on first line of CHANGELOG.md): `9726190`
* Viewer/browser:
* Operating system:

#### Issue variability
Is the issue consistent (can be reproduced consistently) or is it intermittent (only happens sometimes)?:
Consistent
#### Issue

LBAS resupply fails with FindFailed exception if base doesn't need resupplying, usually happens on LBAS that have Toukais loaded which usually don't need resupplying, or when you resupply yourself and continue the script.

Relevant code: 
```        
        for group in self.config.combat['lbas_groups']:
            Util.log_msg("Resupplying LBAS group {}.".format(group))
            if group != 1:
                self.regions['right'].click('lbas_group_tab_{}.png'.format(
                    str(group)))
            Util.check_and_click(self.regions['right'], 'lbas_resupply.png')
            self.regions['right'].waitVanish('lbas_resupply.png', 10)
            if check_fatigue:
                fatigue = self._check_and_manage_lbas_fatigue(fatigue, group)
            Util.kc_sleep(1)
```

Problem is the `waitVanish` call which can throw the FindFailed Exception (sikuli documentation yay :/)

Recommended to use the value returned by `check_and_click()` to decide whether or not to call `waitVanish()`

**Comment by mrmin123** [comment] 2018-03-13 22:54
What version of sikuli are you on? This definitely isn't the behavior I've encountered, since this would happen even if the LBAS squadron never reached a node, and that's happened to me plenty of times.

**Comment by waicool20** [comment] 2018-03-13 22:59
Recently switch to the latest nightly for 1.1.2, which is march 8 build. 1.1.2 is on code freeze tho and they are about to release 1.1.3 soon.

It is indeed possible for `waitVanish` to throw FindFailed tho, tho this might be an unintended change on sikulis end

**Comment by mrmin123** [comment] 2018-03-13 23:03
Yea, I'm guessing this is an issue caused by newer versions of Sikuli since mine is relatively old at this point and does not have this issue.

If this is a major issue for others please downgrade Sikuli until a fix for this is in.

**Closed as completed** 2018-03-18 04:59 UTC
Labels: bug, module:combat
