### ISSUE TITLE
Can't run A3 expeds

### ISSUE THREAD

**Issue by mintgreenrose** [perryhuynh/kcauto#201] opened 2018-08-03 14:11 UTC
console window shuts down automatically after a few seconds with this config:
```# config automatically generated from kcauto frontend (v3.0.0)

[General]
Program: Chrome
JSTOffset: 0
Pause: False

[ScheduledSleep]
ScriptSleepEnabled: False
ScriptSleepStartTime: 0000
ScriptSleepLength: 4
ExpeditionSleepEnabled: False
ExpeditionSleepStartTime: 0000
ExpeditionSleepLength: 3
CombatSleepEnabled: False
CombatSleepStartTime: 0000
CombatSleepLength: 5

[ScheduledStop]
ScriptStopEnabled: False
ScriptStopCount: 
ScriptStopTime: 
ExpeditionStopEnabled: False
ExpeditionStopMode: module
ExpeditionStopCount: 
ExpeditionStopTime: 
CombatStopEnabled: False
CombatStopMode: module
CombatStopCount: 
CombatStopTime: 


[Expeditions]
Enabled: True
Fleet2: A3
Fleet3: 4
Fleet4: 2

[PvP]
Enabled: True
Fleet: 

[Combat]
Enabled: False
Engine: live
Fleets: 
Map: 1-1
FleetMode: 
RetreatNodes: 
NodeSelects: 
Formations: 
NightBattles: 
RetreatLimit: heavy
RepairLimit: moderate
RepairTimeLimit: 0030
LBASGroups: 
LBASGroup1Nodes: 
LBASGroup2Nodes: 
LBASGroup3Nodes: 
MiscOptions: 

[ShipSwitcher]
Enabled: False
Slot1Criteria: 
Slot1Ships: 
Slot2Criteria: 
Slot2Ships: 
Slot3Criteria: 
Slot3Ships: 
Slot4Criteria: 
Slot4Ships: 
Slot5Criteria: 
Slot5Ships: 
Slot6Criteria: 
Slot6Ships: 

[Quests]
Enabled: False
QuestGroups: daily,weekly,monthly
```

But other expeds like Tokyo Express 2 runs on this config

```# config automatically generated from kcauto-kai frontend (v0.4.5)

[General]
Program: Chrome
JSTOffset: 0
Pause: False

[ScheduledSleep]
SleepEnabled: False
SleepStartTime: 0000
SleepLength: 4
ExpeditionSleepEnabled: False
ExpeditionSleepStartTime: 0000
ExpeditionSleepLength: 3
CombatSleepEnabled: False
CombatSleepStartTime: 0000
CombatSleepLength: 5

[Expeditions]
Enabled: True
Fleet2: 38
Fleet3: 4
Fleet4: 2

[PvP]
Enabled: False

[Combat]
Enabled: False
Engine: legacy
Map: 1-5
FleetMode: 
CombatNodes: 4
NodeSelects: 
Formations: A:line_abreast,B:line_abreast,C:line_abreast,I:line_abreast
NightBattles: 
RetreatLimit: heavy
RepairLimit: heavy
RepairTimeLimit: 0000
LBASGroups: 
LBASGroup1Nodes: 
LBASGroup2Nodes: 
LBASGroup3Nodes: 
MiscOptions: CheckFatigue

[ShipSwitcher]
Enabled: False
Slot1Criteria: 
Slot1Ships: 
Slot2Criteria: 
Slot2Ships: 
Slot3Criteria: 
Slot3Ships: 
Slot4Criteria: 
Slot4Ships: 
Slot5Criteria: 
Slot5Ships: 
Slot6Criteria: 
Slot6Ships: 

[Quests]
Enabled: False
```
other than the exped number for fleet 2 I can't seem to find any difference between the two. for it not to work

**Comment by mrmin123** [comment] 2018-08-06 03:00
I can't recreate this issue. If you're still running into this, you'll have to provide more details in terms of what the game is doing to help debug.

**Comment by mrmin123** [comment] 2018-08-18 23:15
Closing due to lack of updates and reproducibility.

**Closed as completed by mrmin123** 2018-08-18 23:15 UTC
Labels: wontfix
